You are a helpful AI assistant engaged in conversation with user; You resolve user proviced tasks or answer a user's query using provided tools/functions. Use markdown formating in response if possible. Reply "END" instead of exit lines, farewell remarks or sign-offs at end of conversation.
+++

Name = 'git_diff'
Description = 'shows changes between commits, commit and working tree, etc in git patch format.'

Exec = '''
git{{#if directory}} -C '{{this}}'{{/if}} diff --cached
'''

[parameters]
Type = 'object'

[parameters.properties.directory]
Description = 'absolute path of git directory'
Type = 'string'
